
import {
  type LucideIcon,
  Network,
  Server,
  Code2,
  Shield,
  Cloud,
  Database,
  BookOpen,
  BrainCircuit,
  Wrench,
  Boxes,
  Sparkles,
  FileCode2,
  Calculator,
} from 'lucide-react';

export type Tool = {
  name: string;
  slug: string;
  description: string;
};

export type ToolCategory = {
  name: string;
  icon: LucideIcon;
  tools: Tool[];
};

export const toolCategories: ToolCategory[] = [
  {
    name: 'Networking & IP Tools',
    icon: Network,
    tools: [
      { name: 'IP Address to Binary Converter', slug: 'ip-to-binary', description: 'Convert IPv4 addresses to binary format.' },
      { name: 'Binary to IP Address Converter', slug: 'binary-to-ip', description: 'Convert binary strings to IPv4 addresses.' },
      { name: 'Subnet Calculator', slug: 'subnet-calculator', description: 'Calculate network ranges, broadcast addresses, and available hosts for any subnet.' },
      { name: 'Subnet Mask Converter', slug: 'subnet-mask-converter', description: 'Convert between CIDR, wildcard, and subnet masks.' },
      { name: 'VLSM Calculator', slug: 'vlsm-calculator', description: 'Design efficient network schemes with Variable Length Subnet Masking.' },
      { name: 'Network Bandwidth Estimator', slug: 'bandwidth-estimator', description: 'Estimate network bandwidth requirements based on usage.' },
      { name: 'Ping / Latency Estimator', slug: 'latency-estimator', description: 'Estimate ping and latency over distances.' },
      { name: 'Data Transfer Time Calculator', slug: 'data-transfer-calculator', description: 'Calculate time to transfer data.' },
      { name: 'MAC Address Validator', slug: 'mac-validator', description: 'Validate MAC address format and find the vendor.' },
      { name: 'Port Number Lookup', slug: 'port-lookup', description: 'Look up common network port numbers.' },
      { name: 'Network Mask Validator', slug: 'network-mask-validator', description: 'Validate a network mask.' },
      { name: 'Public vs Private IP Checker', slug: 'ip-privacy-checker', description: 'Check if an IP is public or private.' },
      { name: 'IP Class Finder', slug: 'ip-class-finder', description: 'Find the class of an IP address.' },
      { name: 'IP Range Generator', slug: 'ip-range-generator', description: 'Generate a list of IP addresses in a range.' },
      { name: 'Broadcast Address Calculator', slug: 'broadcast-address-calculator', description: 'Calculate the broadcast address of a network.' },
      { name: 'Host Count Calculator', slug: 'host-count-calculator', description: 'Calculate the number of hosts in a subnet.' },
      { name: 'Network Address Calculator', slug: 'network-address-calculator', description: 'Calculate the network address (Network ID) of a subnet.' },
      { name: 'CIDR to Subnet List Generator', slug: 'cidr-to-subnet-list', description: 'Generate subnets from a CIDR.' },
      { name: 'CIDR to Wildcard Mask Converter', slug: 'cidr-to-wildcard', description: 'Convert CIDR to wildcard mask.' },
      { name: 'IP Summarization Tool', slug: 'ip-summarization', description: 'Summarize a list of IP networks into a single route.' },
    ],
  },
  {
    name: 'Web & Server Tools',
    icon: Server,
    tools: [
      { name: 'HTTP Header Checker', slug: 'http-header-checker', description: 'Check the HTTP status code of a URL.' },
      { name: 'HTTP Request Size Calculator', slug: 'http-request-size-calculator', description: 'Estimate the size of an HTTP request.' },
      { name: 'SSL Certificate Expiration Checker', slug: 'ssl-expiry-checker', description: 'Check SSL certificate expiration.' },
      { name: 'URL Encoder / Decoder', slug: 'url-encoder-decoder', description: 'Encode or decode URLs.' },
      { name: 'HTML Entity Encoder / Decoder', slug: 'html-entity-encoder-decoder', description: 'Encode or decode HTML entities.' },
      { name: 'HTML / CSS / JS Minifier', slug: 'code-minifier', description: 'Minify HTML, CSS, or JavaScript code.' },
      { name: 'Robots.txt Validator / Generator', slug: 'robots-txt-tool', description: 'Validate or generate a robots.txt file.' },
      { name: 'Sitemap Generator (static)', slug: 'sitemap-generator', description: 'Generate a static XML sitemap.' },
      { name: 'Response Time Calculator', slug: 'response-time-calculator', description: 'Calculate server response time.' },
      { name: 'Domain Expiration Countdown', slug: 'domain-expiry-countdown', description: 'Countdown to domain expiration.' },
      { name: 'SSL Checker', slug: 'ssl-checker', description: 'Check SSL certificate details.' },
      { name: 'Server Uptime Calculator', slug: 'uptime-calculator', description: 'Calculate server uptime percentage.' },
      { name: 'DNS Lookup Tool', slug: 'dns-lookup', description: 'Perform a DNS lookup.' },
      { name: 'Reverse DNS Lookup', slug: 'reverse-dns-lookup', description: 'Perform a reverse DNS lookup.' },
      { name: 'Whois Lookup', slug: 'whois-lookup', description: 'Perform a Whois lookup on a domain.' },
      { name: 'Webpage Load Time Estimator', slug: 'load-time-estimator', description: 'Estimate webpage load time.' },
      { name: 'Cache Expiration Calculator', slug: 'cache-expiry-calculator', description: 'Calculate cache expiration dates.' },
      { name: 'Compression Savings Estimator', slug: 'compression-estimator', description: 'Estimate savings from compression.' },
      { name: 'CDN Bandwidth Estimator', slug: 'cdn-bandwidth-estimator', description: 'Estimate CDN bandwidth usage.' },
    ],
  },
  {
    name: 'Programming & Code',
    icon: Code2,
    tools: [
      { name: 'Code Formatter / Beautifier', slug: 'code-formatter', description: 'Format and beautify your code.' },
      { name: 'JSON Formatter / Validator', slug: 'json-formatter', description: 'Format and validate JSON.' },
      { name: 'Regex Tester / Generator', slug: 'regex-tester', description: 'Test and generate regular expressions.' },
      { name: 'Base64 Encoder / Decoder', slug: 'base64-encoder-decoder', description: 'Encode or decode Base64 strings.' },
      { name: 'Hex ↔ RGB Color Converter', slug: 'color-converter', description: 'Convert between Hex and RGB colors.' },
      { name: 'Binary ↔ Decimal ↔ Hex Converter', slug: 'number-converter', description: 'Convert between number bases.' },
      { name: 'MD5 / SHA Hash Generator', slug: 'hash-generator-md5-sha', description: 'Generate MD5 and SHA hashes.' },
      { name: 'ROT13 Encoder / Decoder', slug: 'rot13-encoder-decoder', description: 'Encode or decode using ROT13 cipher.' },
      { name: 'Caesar Cipher Encoder / Decoder', slug: 'caesar-cipher', description: 'Encode or decode using Caesar cipher.' },
      { name: 'Time Complexity Estimator', slug: 'big-o-calculator', description: 'Estimate Big O time complexity.' },
      { name: 'Prime Number Checker', slug: 'prime-checker', description: 'Check if a number is prime.' },
      { name: 'Fibonacci Sequence Generator', slug: 'fibonacci-generator', description: 'Generate Fibonacci sequence.' },
      { name: 'Factorial Calculator', slug: 'factorial-calculator', description: 'Calculate the factorial of a number.' },
      { name: 'Algorithm Step Simulator', slug: 'algorithm-simulator', description: 'Simulate steps of simple algorithms.' },
      { name: 'Random String Generator', slug: 'random-string-generator', description: 'Generate a random string.' },
      { name: 'Random Number Generator', slug: 'random-number-generator', description: 'Generate a random number.' },
      { name: 'Code Snippet Formatter', slug: 'code-snippet-formatter', description: 'Format a code snippet.' },
      { name: 'Variable Name Validator', slug: 'variable-name-validator', description: 'Validate variable names.' },
      { name: 'Function / Formula Tester', slug: 'function-tester', description: 'Test a function or formula.' },
      { name: 'Unicode / ASCII Converter', slug: 'unicode-ascii-converter', description: 'Convert between Unicode and ASCII.' },
    ],
  },
  {
    name: 'Security & Password',
    icon: Shield,
    tools: [
      { name: 'Password Strength Checker', slug: 'password-strength-checker', description: 'Check the strength of a password.' },
      { name: 'Password Generator', slug: 'password-generator', description: 'Generate secure passwords.' },
      { name: 'Hash Generator', slug: 'hash-generator', description: 'Generate various hashes (MD5, SHA1, SHA256).' },
      { name: 'Encryption / Decryption Tool', slug: 'encryption-decryption-tool', description: 'Encrypt or decrypt text.' },
      { name: 'Two-Factor Auth TOTP Demo', slug: 'totp-demo', description: 'Educational TOTP demo.' },
      { name: 'Base32 / Base58 Encoder / Decoder', slug: 'base32-58-encoder-decoder', description: 'Encode/decode Base32/58.' },
      { name: 'File Integrity Checker', slug: 'file-integrity-checker', description: 'Generate checksums for files.' },
      { name: 'Random Key Generator', slug: 'random-key-generator', description: 'Generate a random encryption key.' },
      { name: 'Private / Public Key Pair Generator', slug: 'key-pair-generator', description: 'Generate a key pair (educational).' },
      { name: 'Secure Token Generator', slug: 'secure-token-generator', description: 'Generate a secure token.' },
      { name: 'OTP Generator', slug: 'otp-generator', description: 'Generate a one-time password.' },
      { name: 'Password Expiry Reminder', slug: 'password-expiry-reminder', description: 'Calculate password expiry.' },
      { name: 'Password Entropy Calculator', slug: 'password-entropy-calculator', description: 'Calculate password entropy.' },
      { name: 'Salting / Hashing Demo Tool', slug: 'salting-hashing-demo', description: 'Demonstrate salting and hashing.' },
      { name: 'Simple Cipher Cracker', slug: 'simple-cipher-cracker', description: 'Educational cipher cracker.' },
      { name: 'Hex to Binary Password Converter', slug: 'hex-to-binary-password', description: 'Convert hex passwords to binary.' },
      { name: 'Binary to ASCII Password Converter', slug: 'binary-to-ascii-password', description: 'Convert binary passwords to ASCII.' },
      { name: 'Random PIN Generator', slug: 'random-pin-generator', description: 'Generate a random PIN.' },
      { name: 'Credential Strength Analyzer', slug: 'credential-strength-analyzer', description: 'Analyze credential strength.' },
      { name: 'Security Quiz Tool', slug: 'security-quiz', description: 'Test your security knowledge.' },
    ],
  },
  {
    name: 'Cloud & Storage Tools',
    icon: Cloud,
    tools: [
      { name: 'Cloud Storage Cost Estimator', slug: 'cloud-storage-cost-estimator', description: 'Estimate cloud storage costs.' },
      { name: 'Bandwidth Cost Calculator', slug: 'bandwidth-cost-calculator', description: 'Calculate bandwidth costs.' },
      { name: 'Backup Storage Requirement', slug: 'backup-storage-calculator', description: 'Calculate backup storage needs.' },
      { name: 'Data Compression Calculator', slug: 'data-compression-calculator', description: 'Calculate data compression.' },
      { name: 'VM RAM & CPU Requirement', slug: 'vm-requirement-estimator', description: 'Estimate VM resource needs.' },
      { name: 'Disk Usage / Partition Estimator', slug: 'disk-usage-estimator', description: 'Estimate disk usage.' },
      { name: 'Cloud Instance Cost Calculator', slug: 'instance-cost-calculator', description: 'Calculate cloud instance costs.' },
      { name: 'Network Transfer Cost Estimator', slug: 'network-transfer-cost-estimator', description: 'Estimate data transfer costs.' },
      { name: 'Storage vs Memory Cost Analyzer', slug: 'storage-memory-cost-analyzer', description: 'Analyze storage vs. memory costs.' },
      { name: 'File Conversion Estimator', slug: 'file-conversion-estimator', description: 'Estimate file conversion sizes.' },
      { name: 'Data Retention Period Calculator', slug: 'data-retention-calculator-cloud', description: 'Calculate data retention periods.' },
      { name: 'Snapshot / Backup Scheduler', slug: 'backup-scheduler', description: 'Schedule snapshots and backups.' },
      { name: 'Storage Growth Estimator', slug: 'storage-growth-estimator', description: 'Estimate storage growth.' },
      { name: 'RAID Storage Calculator', slug: 'raid-calculator', description: 'Calculate RAID storage.' },
      { name: 'Cloud Migration Estimator', slug: 'cloud-migration-estimator', description: 'Estimate cloud migration efforts.' },
      { name: 'Cloud Sync Time Calculator', slug: 'cloud-sync-time-calculator', description: 'Calculate cloud sync time.' },
      { name: 'VM Scaling Calculator', slug: 'vm-scaling-calculator', description: 'Calculate VM scaling needs.' },
      { name: 'Storage Redundancy Calculator', slug: 'storage-redundancy-calculator', description: 'Calculate storage redundancy.' },
      { name: 'Virtual Disk Size Estimator', slug: 'vdisk-size-estimator', description: 'Estimate virtual disk sizes.' },
      { name: 'IOPS Calculator', slug: 'iops-calculator', description: 'Calculate I/O operations per second.' },
    ],
  },
  {
    name: 'Database & Admin Tools',
    icon: Database,
    tools: [
      { name: 'SQL Query Tester', slug: 'sql-query-tester', description: 'Test basic SQL queries.' },
      { name: 'Database Row / Storage Estimator', slug: 'db-storage-estimator', description: 'Estimate database storage.' },
      { name: 'Uptime / Availability Calculator', slug: 'db-uptime-calculator', description: 'Calculate database uptime.' },
      { name: 'Backup Schedule Calculator', slug: 'db-backup-scheduler', description: 'Calculate backup schedules.' },
      { name: 'Data Retention Period Calculator', slug: 'data-retention-calculator-db', description: 'Calculate data retention periods.' },
      { name: 'Replication / Sharding Estimator', slug: 'replication-estimator', description: 'Estimate replication needs.' },
      { name: 'User Quota Calculator', slug: 'user-quota-calculator', description: 'Calculate user quotas.' },
      { name: 'Transaction / TPS Calculator', slug: 'tps-calculator', description: 'Calculate transactions per second.' },
      { name: 'Log Rotation Calculator', slug: 'log-rotation-calculator', description: 'Calculate log rotation schedules.' },
      { name: 'Data Migration Estimator', slug: 'data-migration-estimator', description: 'Estimate data migration efforts.' },
      { name: 'Database Index Size Calculator', slug: 'index-size-calculator', description: 'Calculate database index size.' },
      { name: 'Query Execution Time Estimator', slug: 'query-time-estimator', description: 'Estimate query execution time.' },
      { name: 'Database Growth Calculator', slug: 'db-growth-calculator', description: 'Calculate database growth.' },
      { name: 'Primary / Foreign Key Validator', slug: 'key-validator', description: 'Validate primary/foreign keys.' },
      { name: 'Normalization Checker', slug: 'normalization-checker', description: 'Check database normalization.' },
      { name: 'Duplicate Row Finder', slug: 'duplicate-row-finder', description: 'Find duplicate rows in data.' },
      { name: 'Table Size Estimator', slug: 'table-size-estimator', description: 'Estimate table size.' },
      { name: 'Column Type Converter', slug: 'column-type-converter', description: 'Suggest column type conversions.' },
      { name: 'SQL Injection Tester', slug: 'sql-injection-tester', description: 'Educational SQL injection tester.' },
      { name: 'Database Health Checker', slug: 'db-health-checker', description: 'Basic database health checks.' },
    ],
  },
  {
    name: 'Networking Education',
    icon: BookOpen,
    tools: [
      { name: 'CIDR / Subnet Practice Generator', slug: 'subnet-practice', description: 'Generate subnetting practice problems.' },
      { name: 'IP Quiz / Practice Tool', slug: 'ip-quiz', description: 'Practice IP addressing quizzes.' },
      { name: 'Network Topology Mapper', slug: 'topology-mapper-static', description: 'Static network topology mapper.' },
      { name: 'Port Scanner (educational)', slug: 'port-scanner-edu', description: 'Educational port scanner.' },
      { name: 'DNS Lookup Simulator', slug: 'dns-lookup-simulator', description: 'Simulate DNS lookups.' },
      { name: 'OSI Layer Quiz Tool', slug: 'osi-quiz', description: 'Quiz on the OSI model layers.' },
      { name: 'Packet Size Estimator', slug: 'packet-size-estimator', description: 'Estimate network packet sizes.' },
      { name: 'Firewall Rule Simulator', slug: 'firewall-simulator', description: 'Simulate firewall rules.' },
      { name: 'VPN Bandwidth Estimator', slug: 'vpn-bandwidth-estimator', description: 'Estimate VPN bandwidth needs.' },
      { name: 'MAC Address Quiz Tool', slug: 'mac-address-quiz', description: 'Quiz on MAC addresses.' },
      { name: 'Network Mask Quiz', slug: 'network-mask-quiz', description: 'Quiz on network masks.' },
      { name: 'IP Class Quiz', slug: 'ip-class-quiz', description: 'Quiz on IP address classes.' },
      { name: 'Broadcast Address Quiz', slug: 'broadcast-address-quiz', description: 'Quiz on broadcast addresses.' },
      { name: 'Host Calculation Quiz', slug: 'host-calculation-quiz', description: 'Quiz on calculating hosts.' },
      { name: 'Subnetting Challenge Tool', slug: 'subnetting-challenge', description: 'Challenge your subnetting skills.' },
      { name: 'Routing Table Simulator', slug: 'routing-table-simulator', description: 'Simulate a routing table.' },
      { name: 'NAT Simulation Tool', slug: 'nat-simulator', description: 'Simulate Network Address Translation.' },
      { name: 'VLAN ID Calculator', slug: 'vlan-id-calculator', description: 'Calculate VLAN IDs.' },
      { name: 'IP Summary Quiz', slug: 'ip-summary-quiz', description: 'Quiz on IP summarization.' },
      { name: 'DNS Zone File Quiz', slug: 'dns-zone-file-quiz', description: 'Quiz on DNS zone files.' },
    ],
  },
  {
    name: 'Programming Learning',
    icon: BrainCircuit,
    tools: [
      { name: 'Big-O Complexity Quiz', slug: 'big-o-quiz', description: 'Quiz on Big-O complexity.' },
      { name: 'Algorithm Visualizer', slug: 'algorithm-visualizer', description: 'Visualize sorting/searching algorithms.' },
      { name: 'Recursion Calculator / Simulator', slug: 'recursion-simulator', description: 'Simulate recursive functions.' },
      { name: 'Logic Gate Simulator', slug: 'logic-gate-simulator', description: 'Simulate logic gates.' },
      { name: 'Truth Table Generator', slug: 'truth-table-generator', description: 'Generate truth tables.' },
      { name: 'Boolean Algebra Simplifier', slug: 'boolean-algebra-simplifier', description: 'Simplify boolean algebra expressions.' },
      { name: 'Graph Adjacency Calculator', slug: 'graph-adjacency-calculator', description: 'Calculate graph adjacency.' },
      { name: 'Matrix Operation Calculator', slug: 'matrix-calculator', description: 'Perform matrix operations.' },
      { name: 'Factorial / Combinatorics Calculator', slug: 'combinatorics-calculator', description: 'Calculate factorials and combinations.' },
      { name: 'Fibonacci Sequence Generator (Learning)', slug: 'fibonacci-learner', description: 'Learn about Fibonacci sequence.' },
      { name: 'Prime Number Generator', slug: 'prime-generator', description: 'Generate prime numbers.' },
      { name: 'Binary Tree Simulator', slug: 'binary-tree-simulator', description: 'Simulate a binary tree.' },
      { name: 'Linked List Visualization Tool', slug: 'linked-list-visualizer', description: 'Visualize a linked list.' },
      { name: 'Stack / Queue Simulator', slug: 'stack-queue-simulator', description: 'Simulate stacks and queues.' },
      { name: 'Hash Table Simulator', slug: 'hash-table-simulator', description: 'Simulate a hash table.' },
      { name: 'Search Algorithm Tester', slug: 'search-algorithm-tester', description: 'Test search algorithms.' },
      { name: 'Sorting Algorithm Tester', slug: 'sorting-algorithm-tester', description: 'Test sorting algorithms.' },
      { name: 'Heap Calculator / Simulator', slug: 'heap-simulator', description: 'Simulate a heap.' },
      { name: 'Trie Simulator', slug: 'trie-simulator', description: 'Simulate a trie.' },
      { name: 'Binary Search Tree Visualizer', slug: 'bst-visualizer', description: 'Visualize a binary search tree.' },
    ],
  },
  {
    name: 'ICT Daily Utilities',
    icon: Wrench,
    tools: [
      { name: 'QR Code Generator', slug: 'qr-code-generator', description: 'Generate QR codes for text or URLs.' },
      { name: 'ASCII ↔ Unicode Converter', slug: 'ascii-unicode-converter', description: 'Convert between ASCII and Unicode.' },
      { name: 'Markdown Previewer / Converter', slug: 'markdown-previewer', description: 'Preview and convert Markdown.' },
      { name: 'CSV ↔ JSON Converter', slug: 'csv-json-converter', description: 'Convert between CSV and JSON.' },
      { name: 'Text Case Converter', slug: 'text-case-converter', description: 'Convert text case (UPPER, lower, Title).' },
      { name: 'Word / Character Counter', slug: 'word-counter', description: 'Count words and characters in text.' },
      { name: 'Random Password / Key Generator', slug: 'random-password-key-generator', description: 'Generate random passwords or keys.' },
      { name: 'Random String / Number Generator', slug: 'random-string-number-generator', description: 'Generate random strings or numbers.' },
      { name: 'IP Location Lookup', slug: 'ip-location-lookup', description: 'Look up IP location from a static DB.' },
      { name: 'Color Picker & HEX / RGB Converter', slug: 'color-picker-converter', description: 'Pick colors and convert formats.' },
      { name: 'Dice Roller', slug: 'dice-roller', description: 'Roll virtual dice.' },
      { name: 'Coin Flip Simulator', slug: 'coin-flip', description: 'Simulate a coin flip.' },
      { name: 'Pomodoro Timer', slug: 'pomodoro-timer', description: 'A timer for the Pomodoro technique.' },
      { name: 'Countdown / Timer Generator', slug: 'countdown-generator', description: 'Generate a countdown timer.' },
      { name: 'File Size / Download Time Calculator', slug: 'download-time-calculator', description: 'Calculate download times.' },
      { name: 'Bandwidth Usage Tracker', slug: 'bandwidth-tracker-static', description: 'Static bandwidth usage calculator.' },
      { name: 'Hostname ↔ IP Lookup', slug: 'hostname-ip-lookup', description: 'Look up hostname or IP.' },
      { name: 'Network Packet Estimator', slug: 'network-packet-estimator', description: 'Estimate network packet counts.' },
      { name: 'ASCII Art Generator', slug: 'ascii-art-generator', description: 'Generate ASCII art from text.' },
      { name: 'Emoji / Symbol Picker', slug: 'emoji-picker', description: 'Pick emojis and symbols.' },
    ],
  },
  {
    name: 'Miscellaneous ICT Tools',
    icon: Boxes,
    tools: [
      { name: 'Base Conversion Tool', slug: 'base-converter', description: 'Convert between number bases.' },
      { name: 'URL Shortener (local)', slug: 'url-shortener-local', description: 'A local/static URL shortener.' },
      { name: 'Hex Color Code Analyzer', slug: 'hex-color-analyzer', description: 'Analyze hex color codes.' },
      { name: 'Binary Pattern Finder', slug: 'binary-pattern-finder', description: 'Find patterns in binary data.' },
      { name: 'Random MAC Address Generator', slug: 'random-mac-generator', description: 'Generate a random MAC address.' },
      { name: 'Random IPv6 Generator', slug: 'random-ipv6-generator', description: 'Generate a random IPv6 address.' },
      { name: 'Simple File Encryption / Decryption', slug: 'simple-file-encryption', description: 'Simple file encryption tool.' },
      { name: 'CSV / Excel Analyzer', slug: 'csv-analyzer', description: 'Analyze CSV/Excel data with basic formulas.' },
      { name: 'Code Snippet Sharing Tool', slug: 'snippet-sharing-tool', description: 'Share code snippets.' },
      { name: 'Code Diff Checker', slug: 'code-diff-checker', description: 'Check differences between code snippets.' },
      { name: 'Algorithm Step Logger', slug: 'algorithm-step-logger', description: 'Log steps of an algorithm.' },
      { name: 'Syntax Highlighter / Preview', slug: 'syntax-highlighter', description: 'Highlight and preview code syntax.' },
      { name: 'Markdown to HTML Converter', slug: 'markdown-to-html', description: 'Convert Markdown to HTML.' },
      { name: 'CSS Grid Generator', slug: 'css-grid-generator', description: 'Generate CSS grid layouts.' },
      { name: 'Flexbox Layout Generator', slug: 'flexbox-generator', description: 'Generate Flexbox layouts.' },
      { name: 'JSON to CSV Converter', slug: 'json-to-csv', description: 'Convert JSON to CSV.' },
      { name: 'CSV to JSON Converter', slug: 'csv-to-json', description: 'Convert CSV to JSON.' },
      { name: 'HTML Table Generator from CSV', slug: 'html-table-from-csv', description: 'Generate HTML table from CSV data.' },
      { name: 'IP Ping Simulator', slug: 'ip-ping-simulator', description: 'Simulate an IP ping.' },
    ],
  },
];

export const allTools: Tool[] = toolCategories.flatMap(category => category.tools);

export const mainNavLinks = [
    {
        name: 'AI Tool Recommender',
        href: '/',
        icon: Sparkles,
        description: 'Find the right tool for your task.'
    },
    {
        name: 'AI Code Generator',
        href: '/tools/code-generator',
        icon: FileCode2,
        description: 'Generate and debug code with AI.'
    }
]

    

    

    
