
export const faqData = [
    { question: "What is Two-Factor Authentication (2FA)?", answer: "2FA is a security process where users provide two different authentication factors to verify themselves. It adds a critical second layer of security to your accounts, protecting you even if your password is stolen. The factors are typically 'something you know' (a password) and 'something you have' (your phone)." },
    { question: "How is TOTP different from SMS codes for 2FA?", answer: "TOTP (Time-based One-Time Password) is generated by an app on your device using a shared secret and the current time. It works offline. SMS-based 2FA sends a code to your phone via text message. TOTP is generally considered more secure because SMS messages can be intercepted by sophisticated 'SIM-swapping' attacks." },
    { question: "What is the 'shared secret'?", answer: "The shared secret is a unique, random string of characters generated by a website when you first enable 2FA. This secret is shared exactly once—when you scan the QR code. From then on, both the server and your authenticator app use this secret to generate the same time-based codes without ever transmitting the secret again." },
    { question: "Is it safe to scan the QR code in this demo?", answer: "Yes. The secret key and QR code are generated entirely in your browser and are not stored anywhere. You can add it to your authenticator app for the purpose of this demo and simply delete it from your app when you are finished." },
    { question: "Why does the code change every 30 seconds?", answer: "This is a standard part of the TOTP algorithm. The 30-second 'time step' is a security feature. It ensures that even if an attacker were to somehow see your code, it would become useless very quickly, limiting the window of opportunity for misuse." },
    { question: "What happens if my phone's clock is wrong?", answer: "A significant time difference between your phone and the server will cause the generated codes to mismatch, and you won't be able to log in. Most authenticator apps have a 'time sync' feature in their settings to correct the clock by syncing with Google's time servers, which resolves this issue." },
    { question: "What should I do if I lose my phone with my authenticator app?", answer: "This is why it is critical to save the 'backup codes' provided by a service when you first set up 2FA. These one-time-use codes are your only way to regain access to your account if you lose your second factor. Store them in a safe, secure place, like a password manager or a physical safe." },
    { question: "What is HMAC-SHA1?", answer: "HMAC (Hash-based Message Authentication Code) is a specific type of message authentication code involving a cryptographic hash function and a secret key. SHA1 is the hash function. In TOTP, HMAC-SHA1 is used to combine the shared secret and the current time step to produce a secure, unique hash that is then converted into your 6-digit code." },
    { question: "Can I use the same authenticator app for all my accounts?", answer: "Yes. Apps like Google Authenticator, Microsoft Authenticator, or Authy are based on the same open standard and can be used to manage 2FA for hundreds of different services, from Google and Facebook to your bank and gaming accounts." },
    { question: "Does 2FA make me completely unhackable?", answer: "No security measure is absolute, but 2FA makes you a much, much harder target. While sophisticated phishing attacks can still trick users into giving away their password and 2FA code in real-time, it protects against the vast majority of automated and common attacks that rely on stolen passwords alone. It is one of the most effective security measures you can enable." },
];

export const howToSchema = {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Use the TOTP Demo',
    description: 'A step-by-step guide to understanding how TOTP-based two-factor authentication works.',
    step: [
        { '@type': 'HowToStep', name: 'Generate Secret Key', text: 'The tool automatically generates a secret key and a QR code. This simulates what a website does when you enable 2FA.' },
        { '@type': 'HowToStep', name: 'Scan QR Code', text: 'Open your authenticator app (like Google Authenticator or Authy) on your phone, choose to add a new account, and scan the QR code displayed in the tool.' },
        { '@type': 'HowToStep', name: 'Observe Synchronization', text: 'Your app will now display a 6-digit code that changes every 30 seconds. Notice that it perfectly matches the "Server\'s Current Code" in the demo.' },
        { '@type': 'HowToStep', name: 'Verify a Code', text: 'To simulate a login, type the code from your app into the verification field and click "Verify". The tool will confirm if it matches the code generated for the current time step.' },
    ],
    totalTime: 'PT2M'
};

export const keyTerminologies = [
    { term: '2FA/MFA', definition: 'Two-Factor or Multi-Factor Authentication. A security method requiring two or more pieces of evidence (factors) to grant access.' },
    { term: 'TOTP (Time-based One-Time Password)', definition: 'An algorithm that computes a one-time password from a shared secret key and the current time.' },
    { term: 'Shared Secret', definition: 'A unique key generated by a service and shared with a user\'s authenticator app. It is the basis for all future TOTP calculations.' },
    { term: 'Authenticator App', definition: 'A mobile application (e.g., Google Authenticator, Authy) that stores shared secrets and generates TOTP codes.' },
    { term: 'HMAC (Hash-based Message Authentication Code)', definition: 'A type of cryptographic hash function that uses a secret key. It is used in TOTP to combine the shared secret with the current time step.' },
    { term: 'Time Step', definition: 'A fixed interval of time (usually 30 seconds) used in the TOTP algorithm. A new code is generated at the start of each time step.' },
];
