
import { PageHeader } from '@/components/page-header';
import { SitemapGenerator } from './sitemap-generator';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { StructuredData } from '@/components/structured-data';
import { Lightbulb, AlertTriangle, BookOpen, ChevronRight, Wand } from 'lucide-react';
import Link from 'next/link';

export const metadata = {
    title: 'XML Sitemap Generator (Static) | ICT Toolbench',
    description: 'Create a static XML sitemap for your website to improve SEO. Our generator helps you build a clean, valid sitemap to submit to Google and other search engines.',
    openGraph: {
        title: 'XML Sitemap Generator (Static) | ICT Toolbench',
        description: 'Easily generate a custom XML sitemap to help search engine crawlers discover and index all the pages on your site.',
        url: '/tools/sitemap-generator',
    }
};

const faqData = [
    { question: "What is an XML sitemap?", answer: "An XML sitemap is a text file that lists all the important pages on a website. It acts as a roadmap for search engine crawlers, helping them to find, understand, and index your content more efficiently. It can also provide valuable metadata about each page, such as when it was last updated and its importance relative to other pages." },
    { question: "Is a sitemap required for SEO?", answer: "While not strictly required, a sitemap is a fundamental part of technical SEO and is highly recommended. For large websites, sites with complex navigation, or new sites with few external links, a sitemap is crucial for ensuring that search engines can discover all of your pages." },
    { question: "Where do I put the sitemap.xml file?", answer: "You should place your `sitemap.xml` file in the root directory of your website, making it accessible at `https://yourdomain.com/sitemap.xml`. After uploading it, you should submit its location to search engines via their respective webmaster tools, like Google Search Console and Bing Webmaster Tools." },
    { question: "What is the difference between a static and a dynamic sitemap?", answer: "A static sitemap, which this tool generates, is a manually created file. It's perfect for smaller websites where the content doesn't change very often. A dynamic sitemap is automatically generated by a server-side script or a CMS (like WordPress) and is updated whenever new content is added or removed. Dynamic sitemaps are essential for large, frequently updated sites like blogs or e-commerce stores." },
    { question: "What are the `<lastmod>`, `<changefreq>`, and `<priority>` tags?", answer: "`<lastmod>` indicates the date the file was last modified. `<changefreq>` provides a hint to crawlers about how often the page is likely to change (e.g., 'daily', 'weekly'). `<priority>` specifies the importance of a URL relative to other URLs on your site, on a scale from 0.0 to 1.0. While useful, search engines like Google have stated that they largely ignore `<priority>` and `<changefreq>` in favor of their own signals." },
    { question: "How many URLs can I include in one sitemap?", answer: "A single sitemap file is limited to 50,000 URLs and must not be larger than 50MB when uncompressed. If your site is larger than this, you must create multiple sitemap files and reference them in a 'sitemap index file', which is a sitemap that points to other sitemaps." },
    { question: "Should I include every single page of my site in the sitemap?", answer: "No. You should only include your canonical, high-quality pages that you want search engines to index. Exclude non-canonical URLs, duplicate content, pages blocked by robots.txt, and low-value pages like internal search results or expired listings." },
    { question: "How does a sitemap relate to a `robots.txt` file?", answer: "They work together. A `robots.txt` file tells crawlers which pages they *should not* access. A sitemap tells crawlers which pages they *should* access and provides metadata about them. It is a best practice to include a link to your sitemap in your `robots.txt` file using the `Sitemap:` directive. You can use our <a href='/tools/robots-txt-tool' class='text-primary hover:underline'>robots.txt Generator</a> to create this file." },
    { question: "Is it safe to use this generator?", answer: "Yes. This tool is entirely client-side. All the data you enter and the sitemap that is generated exist only within your browser. No information is sent to our servers." },
    { question: "What format should the `<lastmod>` date be in?", answer: "The date must be in W3C Datetime format. This tool automatically formats the date for you, but the standard format is YYYY-MM-DD (e.g., `2024-10-26`). You can also include time for more precision." }
];

const howToSchema = {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Generate a Static XML Sitemap',
    description: 'A step-by-step guide to creating an XML sitemap for your website.',
    step: [
        { '@type': 'HowToStep', name: 'Add URLs', text: 'For each page you want to include in the sitemap, click the "+ Add URL" button. This will create a new row in the generator.' },
        { '@type': 'HowToStep', name: 'Enter URL Details', text: 'In each row, paste the full URL of the page. You can also specify its last modification date, how frequently it changes, and its priority relative to other pages on your site.' },
        { '@type': 'HowToStep', name: 'Generate the Sitemap', text: 'Click the "Generate Sitemap" button. The tool will instantly create the properly formatted XML content in the output box.' },
        { '@type': 'HowToStep', name: 'Copy and Save', text: 'Click the "Copy" button to copy the XML content. Paste this content into a new text file and save it as `sitemap.xml`.' },
        { '@type': 'HowToStep', name: 'Upload and Submit', text: 'Upload the `sitemap.xml` file to the root directory of your website. Then, submit the sitemap URL (e.g., `https://yourdomain.com/sitemap.xml`) to Google Search Console and Bing Webmaster Tools.' }
    ],
    totalTime: 'PT5M'
};

const keyTerminologies = [
    { term: 'XML Sitemap', definition: 'A file that lists the URLs for a site, allowing search engines to more intelligently crawl the site\'s content.' },
    { term: 'URLset', definition: 'The root XML tag that encapsulates all the URLs in a sitemap.' },
    { term: 'User-agent', definition: 'The name of the web crawler (e.g., Googlebot) that reads the sitemap.' },
    { term: '<loc>', definition: 'The XML tag that specifies the absolute URL of a page. This is the only mandatory tag for each entry.' },
    { term: '<lastmod>', definition: 'An optional tag that indicates the date the file was last modified, in YYYY-MM-DD format.' },
    { term: '<changefreq>', definition: 'An optional tag that provides a hint to crawlers on how frequently the page is likely to change (e.g., "daily", "monthly").' },
    { term: '<priority>', definition: 'An optional tag that signifies the importance of a URL relative to other URLs on your site (0.0 to 1.0).' },
    { term: 'Sitemap Index File', definition: 'A sitemap that contains a list of other sitemaps. Used for sites with more than 50,000 URLs.' },
];

export default function SitemapGeneratorPage() {
  return (
    <>
      <StructuredData data={faqData.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer.replace(/<[^>]*>?/gm, '') } }))} />
      <StructuredData data={howToSchema} />
      <PageHeader
        title="Sitemap Generator (Static)"
        description="Create a simple, static XML sitemap for your website. This tool helps you build a clean sitemap file to guide search engines in crawling and indexing your content."
      />
      
      <div className="max-w-4xl mx-auto space-y-12">
        <SitemapGenerator />

        <section>
          <h2 className="text-2xl font-bold mb-4">How to Use This Tool</h2>
          <Card className="prose prose-sm max-w-none text-foreground p-6">
              <p>This generator simplifies the creation of a static `sitemap.xml` file, an essential component for good technical SEO.</p>
              <ol>
                  <li><strong>Add URL Entries:</strong> For each page you want to include in your sitemap, click the "+ Add URL" button to create a new row.</li>
                  <li><strong>Fill in the Details:</strong> For each row, provide the following information:
                    <ul>
                        <li><strong>URL:</strong> The full, absolute URL of the page (e.g., `https://yourdomain.com/about-us`). This is the only required field.</li>
                        <li><strong>Last Modified:</strong> (Optional) The date the page was last updated.</li>
                        <li><strong>Change Frequency:</strong> (Optional) A hint to crawlers about how often the page changes.</li>
                        <li><strong>Priority:</strong> (Optional) The importance of this page relative to others on your site (from 0.0 to 1.0).</li>
                    </ul>
                  </li>
                  <li><strong>Generate Sitemap:</strong> Once you have added all your URLs, click the "Generate Sitemap" button.</li>
                  <li><strong>Copy and Save:</strong> The complete XML content will appear in the output box. Use the "Copy" button to copy it. Paste the content into a text editor and save the file as `sitemap.xml`.</li>
                  <li><strong>Upload and Submit:</strong> Upload this file to the root directory of your website. Finally, submit the path to your sitemap (e.g., `https://yourdomain.com/sitemap.xml`) in Google Search Console and Bing Webmaster Tools.</li>
              </ol>
          </Card>
        </section>

        <section>
           <h2 className="text-2xl font-bold mb-4">Key Terminologies</h2>
           <Card>
              <CardContent className="p-6">
                  <dl className="space-y-4">
                      {keyTerminologies.map((item) => (
                          <div key={item.term}>
                              <dt className="font-semibold">{item.term}</dt>
                              <dd className="text-muted-foreground text-sm">{item.definition}</dd>
                          </div>
                      ))}
                  </dl>
              </CardContent>
           </Card>
      </section>

      <Card className='bg-secondary/30 border-primary/20'>
          <CardHeader>
              <div className='flex items-center gap-2 text-primary'>
                  <BookOpen className="h-6 w-6" aria-hidden="true" />
                  <CardTitle className="text-primary">Educational Deep Dive: The Importance of Sitemaps in SEO</CardTitle>
              </div>
              <CardDescription>Understand how sitemaps work, why they are a cornerstone of technical SEO, and how to use them effectively.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6 prose prose-lg max-w-none text-foreground">
              <section>
                  <h3 className="font-bold text-xl">What is an XML Sitemap? Your Website's Roadmap for Robots</h3>
                  <p>
                    An XML Sitemap is a file that lists every important URL on your website that you want to be discovered and indexed by search engines. It acts as a direct line of communication to crawlers like Googlebot, providing a clear and organized map of your content. While search engines can discover pages by following links, a sitemap guarantees that they know about all the pages you consider important, even if those pages don't have many internal or external links pointing to them.
                  </p>
                  <p>
                    Beyond just listing URLs, a sitemap can provide valuable metadata for each page, including when it was last updated, how often it changes, and its priority relative to other pages. This helps search engines make more intelligent decisions about how to crawl your site.
                  </p>
              </section>
              <section>
                  <h3 className="font-bold text-xl">When is a Sitemap Most Critical?</h3>
                  <p>While every site benefits from a sitemap, it becomes especially crucial in certain scenarios:</p>
                  <ul className="list-disc pl-5">
                     <li><strong>Large Websites:</strong> If your site has thousands of pages, it's easy for crawlers to miss new or updated content during their regular crawl. A sitemap ensures all pages are on their radar.</li>
                     <li><strong>New Websites:</strong> A brand-new site with few external backlinks is like an island. A sitemap is the first map you give to search engines to help them find and explore your content.</li>
                     <li><strong>Sites with Complex Navigation:</strong> If your site has a deep or complex structure, or uses navigation that crawlers struggle with (like heavy JavaScript), some pages may be "orphaned" or hard to find. A sitemap provides a direct path to these pages.</li>
                     <li><strong>Sites with Rich Media:</strong> You can create specialized sitemaps for video, image, and news content, providing additional metadata to help this content appear in relevant search results.</li>
                  </ul>
              </section>
               <section>
                  <h3 className="font-bold text-xl">Sitemaps and `robots.txt`: A Powerful Duo</h3>
                    <p>
                        A sitemap and a `robots.txt` file are two sides of the same coin. The `robots.txt` file tells crawlers where they are <strong>not allowed</strong> to go. The sitemap tells them where they <strong>should</strong> go.
                    </p>
                    <p>
                        It is a universal best practice to include a reference to your sitemap in your `robots.txt` file. This is done with a simple directive:
                    </p>
                     <div className="bg-muted p-4 rounded-md font-code text-sm">
                        Sitemap: https://www.yourdomain.com/sitemap.xml
                    </div>
                     <p>
                        This is often the first place a crawler looks to discover your sitemap. You can create your `robots.txt` file using our <Link href="/tools/robots-txt-tool" className="text-primary hover:underline">Robots.txt Generator & Validator</Link>.
                    </p>
              </section>
          </CardContent>
      </Card>

      <div className="grid md:grid-cols-2 gap-8">
          <Card>
              <CardHeader>
                  <div className='flex items-center gap-2'><Wand className="h-6 w-6 text-accent" /> <CardTitle>Pro Tips & Quick Hacks</CardTitle></div>
              </CardHeader>
              <CardContent>
                  <ul className="list-disc pl-5 space-y-3 text-sm text-muted-foreground">
                      <li><strong>Be Consistent:</strong> Ensure all URLs listed in your sitemap use the same protocol (http vs. https) and domain version (www vs. non-www) as your canonical URLs.</li>
                      <li><strong>Keep it Clean:</strong> Regularly audit your sitemap to remove any URLs that result in a 404 error or redirect. A clean sitemap reflects a well-maintained website.</li>
                      <li><strong>Sitemap Index for Large Sites:</strong> If you have more than 50,000 URLs, create a sitemap index file. This is a sitemap that points to other sitemaps, allowing you to manage your URLs in logical groups (e.g., a separate sitemap for products, blog posts, etc.).</li>
                      <li><strong>Use `lastmod` for Freshness:</strong> The `&lt;lastmod&gt;` tag is the most useful piece of optional data. For frequently updated pages, keeping this date accurate can encourage search engines to crawl them more often.</li>
                  </ul>
              </CardContent>
          </Card>
          <Card>
              <CardHeader>
                   <div className='flex items-center gap-2'><AlertTriangle className="h-6 w-6 text-destructive" /> <CardTitle>Common Mistakes to Avoid</CardTitle></div>
              </CardHeader>
              <CardContent>
                   <ul className="list-disc pl-5 space-y-3 text-sm text-muted-foreground">
                      <li><strong>Including Blocked URLs:</strong> Never include a URL in your sitemap that is disallowed by your `robots.txt` file. This sends a conflicting signal to search engines.</li>
                      <li><strong>Using Relative URLs:</strong> All URLs in a sitemap must be absolute, meaning they must start with the full protocol and domain name (e.g., `https://www.example.com/page`).</li>
                      <li><strong>Forgetting to Submit:</strong> Simply uploading the `sitemap.xml` file is not enough. You must submit its location to Google Search Console and Bing Webmaster Tools to ensure they know it exists.</li>
                      <li><strong>"Set It and Forget It":</strong> For a static site, you must manually update your sitemap whenever you add, remove, or significantly change a page. Forgetting to do so will result in an outdated roadmap for crawlers.</li>
                  </ul>
              </CardContent>
          </Card>
      </div>

       <section>
          <h2 className="text-2xl font-bold mb-4">Frequently Asked Questions</h2>
          <Card>
              <CardContent className="p-6">
                  <Accordion type="single" collapsible className="w-full">
                      {faqData.map((item, index) => (
                          <AccordionItem value={`item-${index}`} key={index}>
                              <AccordionTrigger>{item.question}</AccordionTrigger>
                              <AccordionContent>
                                <div dangerouslySetInnerHTML={{ __html: item.answer }} />
                              </AccordionContent>
                          </AccordionItem>
                      ))}
                  </Accordion>
              </CardContent>
          </Card>
      </section>

      <section>
          <h2 className="text-2xl font-bold mb-4">Related Tools</h2>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              <Link href="/tools/robots-txt-tool" className="block">
                  <Card className="hover:border-primary transition-colors h-full">
                      <CardHeader>
                          <CardTitle className="text-base flex items-center justify-between">Robots.txt Validator / Generator<ChevronRight className="h-4 w-4 text-muted-foreground" /></CardTitle>
                          <CardDescription className="text-xs">Create the `robots.txt` file where you will link to your new sitemap.</CardDescription>
                      </CardHeader>
                  </Card>
              </Link>
              <Link href="/tools/http-header-checker" className="block">
                  <Card className="hover:border-primary transition-colors h-full">
                      <CardHeader>
                          <CardTitle className="text-base flex items-center justify-between">HTTP Header Checker<ChevronRight className="h-4 w-4 text-muted-foreground" /></CardTitle>
                          <CardDescription className="text-xs">Check that your sitemap URLs return a `200 OK` status code.</CardDescription>
                      </CardHeader>
                  </Card>
              </Link>
               <Link href="/tools/url-encoder-decoder" className="block">
                  <Card className="hover:border-primary transition-colors h-full">
                      <CardHeader>
                          <CardTitle className="text-base flex items-center justify-between">URL Encoder / Decoder<ChevronRight className="h-4 w-4 text-muted-foreground" /></CardTitle>
                          <CardDescription className="text-xs">Ensure any special characters in your URLs are properly encoded before adding them to a sitemap.</CardDescription>
                      </CardHeader>
                  </Card>
              </Link>
          </div>
      </section>
      </div>
    </>
  );
}
