
export const faqData = [
    { question: "What is a file checksum or hash?", answer: "A checksum or hash is a small, fixed-size string of text that is algorithmically generated from the contents of a file. It acts as a unique 'digital fingerprint.' If even a single bit of the file changes, the checksum will change completely. This allows you to verify that a file has not been altered or corrupted." },
    { question: "Why is file integrity important?", answer: "When you download a file from the internet, there's a risk it could be corrupted during transit or, worse, maliciously modified by an attacker to include malware. Verifying the file's checksum against the one provided by the official source is the best way to ensure the file is authentic and safe to use." },
    { question: "How do I verify a file using this tool?", answer: "1. Download the file to your computer. 2. Find the official checksum (e.g., SHA-256) provided on the download page. 3. Use this tool to generate the checksum for your downloaded file. 4. Compare the hash generated by this tool with the one from the website. If they match exactly, the file is authentic." },
    { question: "Is this tool secure? Is my file uploaded anywhere?", answer: "This tool is 100% secure and private. All calculations are performed directly in your web browser using JavaScript. Your file is never uploaded to our server or any other server, ensuring your data remains on your computer." },
    { question: "What's the difference between MD5, SHA-1, and SHA-256?", answer: "They are different hashing algorithms with varying levels of security. **MD5** and **SHA-1** are older and now considered cryptographically insecure, as 'collisions' (two different files producing the same hash) can be created. They should only be used for checking against accidental corruption. **SHA-256** is the current industry standard and is secure against both corruption and malicious tampering." },
    { question: "Which hash algorithm should I use?", answer: "You should always use the most secure algorithm offered by the file's provider. If a SHA-256 hash is available, use that one for your comparison. If only an MD5 or SHA-1 hash is provided, use that, but be aware that it offers weaker protection against deliberate tampering." },
    { question: "Can this tool check very large files?", answer: "Yes, but performance will depend on your computer's processing power. For very large files (multiple gigabytes), the browser may become slow or unresponsive while it reads and processes the file's contents. For such files, a command-line tool may be more efficient." },
    { question: "What is a 'collision' in hashing?", answer: "A collision is when two different input files produce the exact same hash output. For a secure hash function, this should be computationally infeasible. The discovery of practical collision attacks against MD5 and SHA-1 is why they are no longer recommended for security applications." },
    { question: "Why don't the hashes match?", answer: "If the hashes do not match, it means the file you have is not identical to the original. Do not use the file. The most common reasons are: 1) The file was corrupted during download. 2) The file was maliciously modified. 3) You are comparing against the wrong hash or using the wrong algorithm. Try downloading the file again from the official source." },
    { question: "How does this relate to the Hash Generator tool?", answer: "Our <a href='/tools/hash-generator-md5-sha' class='text-primary hover:underline'>Hash Generator</a> works on text input, while this tool works on entire files. Both use the same underlying cryptographic hash functions to produce a digital fingerprint." },
];

export const howToSchema = {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: 'How to Use the File Integrity Checker',
    description: 'A step-by-step guide to generating and verifying file checksums.',
    step: [
        { '@type': 'HowToStep', name: 'Select File', text: 'Click "Choose File" and select a file from your local device.' },
        { '@type': 'HowToStep', name: 'Generate Checksums', text: 'Click the "Generate Checksums" button to start the hashing process. This happens entirely in your browser.' },
        { '@type': 'HowToStep', name: 'Compare Hashes', text: 'Compare the generated MD5, SHA-1, SHA-256, or SHA-512 hash with the one provided by the source of the file.' },
        { '@type': 'HowToStep', name: 'Verify Integrity', text: 'If the hashes match exactly, the file is authentic and has not been altered. If they do not match, do not use the file and download it again.' },
    ],
    totalTime: 'PT1M'
};

export const keyTerminologies = [
    { term: 'Checksum', definition: 'A small-sized block of data derived from a block of digital data for the purpose of detecting errors. A cryptographic hash is a secure form of checksum.' },
    { term: 'Hash Function', definition: 'A mathematical algorithm that maps data of arbitrary size to a fixed-size string of characters. It is a one-way function.' },
    { term: 'SHA-256', definition: 'A secure, 256-bit hash function that is the current industry standard for data integrity and digital signatures.' },
    { term: 'MD5', definition: 'An older, 128-bit hash function that is no longer considered secure against malicious attacks but is still used for basic file corruption checks.' },
    { term: 'Integrity', definition: 'The property that data has not been altered or tampered with in an unauthorized manner.' },
    { term: 'Collision', definition: 'A situation where two different inputs produce the same hash output